export const RECEIVE_DOCS = "RECEIVE_DOCS";
export const RECEIVE_TOC = "RECEIVE_TOC";
export const REQUEST_DOCS = "REQUEST_DOCS";
export const REQUEST_TOC = "REQUEST_TOC";

export const SET_WINDOW_HEIGHT = "SET_WINDOW_HEIGHT";
export const SET_WINDOW_SIZE = "SET_WINDOW_SIZE";
export const SET_WINDOW_WIDTH = "SET_WINDOW_SIZE";
